### PR TITLE
Readme Updates and Misc Cleanup

### PR DESCRIPTION
**Pull request by napalm684**
Added further instruction for getting up and running.
Some miscellaneous formatting/spelling issues resolved.

### CODE REVIEW

**Comment by napalm684** [comment]
@Layla-P is there an issue with this PR?

**Review by rickvdbosch — APPROVED** [review]
Looks good

**Comment by Layla-P** [comment]
> @Layla-P is there an issue with this PR?

Only issue is my lack of time!!

**Review by Layla-P — APPROVED** [review]
Thanks for the updates and cleanup!

**Pull request merged**
